modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/Example/${repo}/issues"
license = "GPLv3"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Example Author"
credits = "Example Contributor"
description = "This is an example starter template."
displayURL = "https://example.com"
#updateJSONURL = ""
#logoFile = ""

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"
